/* AUTO-GENERATED by scripts scratchpad from public/_generated/hidamari-hifuka/*.
 * The clinic-site static template: theme-variable-driven CSS + the progressive-enhancement
 * script + decorative / placeholder SVGs. Every generated site ships an identical copy of these;
 * only the per-clinic HTML content and the .nj-site inline CSS custom properties differ.
 * Edit the source bundle and re-run the generator rather than hand-editing this file. */

export const CSS: Record<string, string> = {
  "base.css": `/* ひだまり皮ふ科クリニック — base.css
 * Design DNA: nishinomiya-hifuka.com（水彩のにじみ + 繊細な植物線画 + やわらかい丸/筆書体 +
 *   くすんだ水色の見出しラベル + ダスティピンクの予約CTA。とにかく「やさしい・女性向け・
 *   家族で通える」。影はほぼ無し、角は控えめに丸い、余白はゆったり）。
 * 参考サイトの class 名・マークアップ・画像は一切流用していない。 */

.nj-site {
  /* --- color（水色は見出しラベル、ピンクは予約導線。本文はあたたかいグレー） --- */
  --nj-primary: #7aa9d8;
  --nj-primary-deep: #4f7aa6;
  --nj-accent: #dd93b0;
  --nj-tint: #f8f3ea;
  --nj-paper: #fffdf8;
  --nj-ink: #4a453f;
  --nj-ink-soft: #8b8579;
  --nj-line: #ece3d2;

  /* 水彩のにじみに使うパステル */
  --nj-wash-pink: #f2cdd6;
  --nj-wash-blue: #c9dcee;
  --nj-wash-yellow: #f3e7b6;
  --nj-wash-peach: #f4d6c0;
  --nj-wash-mint: #d0e4d8;
  --nj-botanical: #c9bda4;

  /* --- type（見出し = Klee One の筆書体、本文 = Zen Kaku Gothic New） --- */
  --nj-font-head: "Klee One", "Hiragino Maru Gothic ProN", "Yu Gothic", serif;
  --nj-font-body: "Zen Kaku Gothic New", "Hiragino Sans", "Yu Gothic", sans-serif;
  --nj-head-tracking: 0.09em;

  /* --- layout（狭めのコンテナ = 参考サイトの主段は ~850px） --- */
  --nj-container: 920px;
  --nj-gutter: clamp(1.25rem, 5vw, 2.25rem);
  --nj-section-pad: 88px;

  /* --- spacing scale --- */
  --nj-s1: 4px;
  --nj-s2: 8px;
  --nj-s3: 12px;
  --nj-s4: 16px;
  --nj-s5: 24px;
  --nj-s6: 36px;
  --nj-s7: 56px;
  --nj-s8: 80px;
  --nj-s9: 120px;

  --nj-radius-sm: 6px;
  --nj-radius-md: 14px;
  --nj-radius-lg: 24px;
  --nj-radius-pill: 999px;

  font-family: var(--nj-font-body);
  color: var(--nj-ink);
  background: var(--nj-paper);
  line-height: 1.85;
  letter-spacing: 0.02em;
  -webkit-font-smoothing: antialiased;
  overflow-x: clip;
}

html,
body {
  margin: 0;
  padding: 0;
}

.nj-site *,
.nj-site *::before,
.nj-site *::after {
  box-sizing: border-box;
}

/* :where() = 詳細度 0。セクション側の単一クラスが必ず勝つ。 */
.nj-site :where(h1, h2, h3, h4, p, figure, dl, dd, ul, ol) {
  margin: 0;
}
.nj-site :where(ul, ol) {
  padding: 0;
  list-style: none;
}
.nj-site :where(a) {
  color: inherit;
  text-decoration: none;
}
.nj-site :where(img) {
  display: block;
  max-width: 100%;
  height: auto;
}

.nj-site h1,
.nj-site h2,
.nj-site h3,
.nj-site h4 {
  font-family: var(--nj-font-head);
  font-weight: 600;
  letter-spacing: var(--nj-head-tracking);
  line-height: 1.55;
  word-break: auto-phrase;
  color: var(--nj-ink);
}

/* --- container --- */
.nj-site .container {
  width: 100%;
  max-width: var(--nj-container);
  margin-inline: auto;
  padding-inline: var(--nj-gutter);
}

/* --- section heading（和文・大 + 英字・小・水色） --- */
.nj-site .heading {
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;
  gap: var(--nj-s2);
  margin-bottom: var(--nj-s7);
}
.nj-site .heading .en {
  order: -1;
  font-family: var(--nj-font-head);
  font-size: 0.82rem;
  letter-spacing: 0.28em;
  text-transform: uppercase;
  color: var(--nj-primary);
}
.nj-site .heading .ja {
  font-size: clamp(1.6rem, 1.2rem + 1.7vw, 2.05rem);
}
/* 見出し下の小さな植物の飾り（水彩・植物の DNA に合わせて） */
.nj-site .heading::after {
  content: "";
  width: 96px;
  height: 22px;
  margin-top: var(--nj-s3);
  background: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='96' height='22' viewBox='0 0 96 22'%3E%3Cg fill='none' stroke='%237aa9d8' stroke-width='1.4' stroke-linecap='round'%3E%3Cpath d='M6 11h32M58 11h32'/%3E%3Cpath d='M48 4c2 0 3.6 1.6 3.6 3.6S48 11 48 11s-3.6-1.6-3.6-3.6S46 4 48 4z'/%3E%3Cpath d='M48 18c-2 0-3.6-1.6-3.6-3.6S48 11 48 11s3.6 1.6 3.6 3.6S50 18 48 18z'/%3E%3Cpath d='M41 11c0-2 1.6-3.6 3.6-3.6S48 11 48 11s-1.6 3.6-3.6 3.6S41 13 41 11z'/%3E%3Cpath d='M55 11c0 2-1.6 3.6-3.6 3.6S48 11 48 11s1.6-3.6 3.6-3.6S55 9 55 11z'/%3E%3Ccircle cx='48' cy='11' r='1.3' fill='%237aa9d8'/%3E%3C/g%3E%3C/svg%3E") no-repeat center / contain;
}
.nj-site .philosophy .heading::after {
  filter: brightness(0) invert(1);
  opacity: 0.7;
}

/* --- section base --- */
.nj-site .section {
  position: relative;
  padding-block: var(--nj-section-pad);
  overflow: clip;
}
.nj-site .section--paper { background: var(--nj-paper); }
.nj-site .section--tint { background: var(--nj-tint); }

/* --- 水彩のにじみ（装飾。position:absolute で置く） --- */
.nj-site .wash {
  position: absolute;
  border-radius: 50%;
  filter: blur(34px);
  opacity: 0.5;
  pointer-events: none;
  z-index: 0;
}
.nj-site .wash--pink { background: var(--nj-wash-pink); }
.nj-site .wash--blue { background: var(--nj-wash-blue); }
.nj-site .wash--yellow { background: var(--nj-wash-yellow); }
.nj-site .wash--peach { background: var(--nj-wash-peach); }
.nj-site .wash--mint { background: var(--nj-wash-mint); }

/* --- 植物の線画（inline SVG に付ける） --- */
.nj-site .botanical {
  position: absolute;
  color: var(--nj-botanical);
  pointer-events: none;
  z-index: 0;
}
.nj-site .botanical svg { display: block; width: 100%; height: 100%; }

/* section の中身は装飾より前に */
.nj-site .section > .container { position: relative; z-index: 1; }

/* --- pill button --- */
.nj-site .btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: var(--nj-s2);
  padding: 0.85rem 1.8rem;
  border-radius: var(--nj-radius-pill);
  font-family: var(--nj-font-head);
  font-size: 0.95rem;
  letter-spacing: 0.06em;
  transition: filter 0.2s ease, transform 0.2s ease;
}
.nj-site .btn:hover { filter: brightness(1.05); transform: translateY(-1px); }
.nj-site .btn--reserve { background: var(--nj-accent); color: #fff; }
.nj-site .btn--tel {
  background: #fff;
  color: var(--nj-primary-deep);
  border: 1.5px solid color-mix(in srgb, var(--nj-primary) 45%, transparent);
}

/* --- モーション（js/site.js が .nj-js を付ける。JS 無しなら全部見える） --- */
.nj-site.nj-js :where(.nj-reveal, [data-nj-anim]) {
  opacity: 0;
  transform: translateY(24px);
  transition: opacity 0.7s cubic-bezier(0.22, 0.68, 0.3, 1),
    transform 0.7s cubic-bezier(0.22, 0.68, 0.3, 1);
  transition-delay: var(--nj-anim-delay, 0s);
}
.nj-site.nj-js [data-nj-anim="left"] { transform: translateX(-28px); }
.nj-site.nj-js [data-nj-anim="zoom"] { transform: scale(0.95); }
.nj-site.nj-js .nj-reveal.is-visible,
.nj-site.nj-js [data-nj-anim].is-visible {
  opacity: 1;
  transform: none;
}

/* scroll 進捗バー / ヘッダー影 / アンカーのヘッダー分オフセット */
.nj-site .nj-progress {
  position: fixed;
  inset: 0 auto auto 0;
  z-index: 60;
  width: 0;
  height: 3px;
  background: linear-gradient(90deg, var(--nj-accent), var(--nj-primary));
  transition: width 0.1s linear;
  pointer-events: none;
}
.nj-site header[data-nj-scrolled] {
  box-shadow: 0 6px 22px color-mix(in srgb, var(--nj-primary-deep) 12%, transparent);
}
.nj-site section[id] {
  scroll-margin-top: var(--nj-header-h, 90px);
}

/* きらきら（見出し脇。控えめに） */
@keyframes nj-twinkle {
  0%, 100% { opacity: 0; transform: scale(0.3) rotate(0deg); }
  50% { opacity: 1; transform: scale(1) rotate(45deg); }
}
.nj-site .nj-spark {
  position: absolute;
  width: 10px;
  height: 10px;
  background: var(--nj-accent);
  clip-path: polygon(50% 0, 60% 40%, 100% 50%, 60% 60%, 50% 100%, 40% 60%, 0 50%, 40% 40%);
  opacity: 0;
  pointer-events: none;
}
@media (prefers-reduced-motion: no-preference) {
  .nj-site .nj-spark { animation: nj-twinkle 2.8s ease-in-out infinite; }
}

@media (prefers-reduced-motion: reduce) {
  .nj-site.nj-js :where(.nj-reveal, [data-nj-anim]) { opacity: 1; transform: none; transition: none; }
  .nj-site .nj-progress { display: none; }
  .nj-site .nj-spark { animation: none; opacity: 0.5; }
}
`,
  "header.css": `/* header + 右端の予約レール */
.nj-site .site-header {
  position: sticky;
  top: 0;
  z-index: 50;
  background: color-mix(in srgb, var(--nj-paper) 92%, transparent);
  backdrop-filter: blur(6px);
  border-bottom: 1px solid var(--nj-line);
}
.nj-site .site-header__inner {
  display: flex;
  align-items: center;
  gap: var(--nj-s4);
  max-width: 1180px;
  margin-inline: auto;
  padding: var(--nj-s3) var(--nj-gutter);
}

.nj-site .brand {
  display: flex;
  align-items: center;
  gap: var(--nj-s3);
  margin-right: auto;
  flex-shrink: 0;
}
.nj-site .brand__mark {
  width: 42px;
  height: 42px;
  flex-shrink: 0;
  border-radius: 14px 14px 14px 4px;
  background: linear-gradient(135deg, var(--nj-primary), var(--nj-accent));
  display: grid;
  place-items: center;
}
.nj-site .brand__mark svg { width: 24px; height: 24px; color: #fff; }
.nj-site .brand__name {
  display: flex;
  flex-direction: column;
  line-height: 1.2;
}
.nj-site .brand__ja {
  font-family: var(--nj-font-head);
  font-size: 1.05rem;
  font-weight: 600;
  letter-spacing: 0.04em;
  color: var(--nj-ink);
  white-space: nowrap;
}
.nj-site .brand__en {
  font-size: 0.55rem;
  letter-spacing: 0.18em;
  text-transform: uppercase;
  color: var(--nj-ink-soft);
  white-space: nowrap;
}

.nj-site .nav {
  display: flex;
  align-items: center;
  gap: var(--nj-s4);
  flex-shrink: 0;
}
.nj-site .nav a {
  font-size: 0.86rem;
  color: var(--nj-ink);
  white-space: nowrap;
  padding-block: var(--nj-s2);
  border-bottom: 2px solid transparent;
  transition: color 0.15s ease, border-color 0.15s ease;
}
.nj-site .nav a:hover {
  color: var(--nj-primary-deep);
  border-color: color-mix(in srgb, var(--nj-primary) 50%, transparent);
}

.nj-site .header-cta {
  flex-shrink: 0;
  display: inline-flex;
  align-items: center;
  padding: 0.55rem 1.2rem;
  border-radius: var(--nj-radius-pill);
  background: var(--nj-accent);
  color: #fff;
  font-family: var(--nj-font-head);
  font-size: 0.85rem;
  letter-spacing: 0.05em;
  white-space: nowrap;
}

/* mobile menu machinery（CSS のみ） */
.nj-site .nav-toggle { position: absolute; opacity: 0; pointer-events: none; }
.nj-site .burger {
  display: none;
  width: 30px;
  height: 22px;
  position: relative;
  z-index: 70;
  cursor: pointer;
  flex-shrink: 0;
}
.nj-site .burger span,
.nj-site .burger span::before,
.nj-site .burger span::after {
  content: "";
  position: absolute;
  left: 0;
  width: 100%;
  height: 2px;
  border-radius: 2px;
  background: var(--nj-primary-deep);
  transition: transform 0.2s ease, opacity 0.2s ease;
}
.nj-site .burger span { top: 10px; }
.nj-site .burger span::before { top: -8px; }
.nj-site .burger span::after { top: 8px; }

/* 右端の予約レール（デスクトップ） — 参考サイトの縦ピンクボタン */
.nj-site .rail {
  position: fixed;
  right: 0;
  top: 50%;
  transform: translateY(-50%);
  z-index: 45;
  display: flex;
  flex-direction: column;
  gap: 3px;
}
.nj-site .rail a {
  writing-mode: vertical-rl;
  padding: var(--nj-s5) var(--nj-s2);
  background: var(--nj-accent);
  color: #fff;
  font-family: var(--nj-font-head);
  font-size: 0.82rem;
  letter-spacing: 0.14em;
  border-radius: 10px 0 0 10px;
  transition: filter 0.2s ease;
}
.nj-site .rail a:nth-child(2) { background: color-mix(in srgb, var(--nj-accent) 78%, #7fae7a); }
.nj-site .rail a:nth-child(3) { background: var(--nj-primary); }
.nj-site .rail a:hover { filter: brightness(1.06); }

@media (max-width: 1080px) {
  .nj-site .nav {
    position: fixed;
    inset: 0 0 auto 0;
    z-index: 60;
    flex-direction: column;
    align-items: stretch;
    gap: 0;
    padding: 84px var(--nj-gutter) var(--nj-s6);
    background: var(--nj-paper);
    max-height: 0;
    overflow: hidden;
    transition: max-height 0.3s ease;
    box-shadow: 0 14px 30px rgba(74, 69, 63, 0.1);
  }
  .nj-site .nav a { padding: var(--nj-s4) 0; border-bottom: 1px solid var(--nj-line); }
  .nj-site .burger { display: block; }
  .nj-site .header-cta { display: none; }
  .nj-site .nav-toggle:checked ~ .nav { max-height: 90vh; overflow-y: auto; }
  .nj-site .nav-toggle:checked ~ .burger span { background: transparent; }
  .nj-site .nav-toggle:checked ~ .burger span::before { top: 0; transform: rotate(45deg); }
  .nj-site .nav-toggle:checked ~ .burger span::after { top: 0; transform: rotate(-45deg); }
  .nj-site .rail {
    top: auto;
    bottom: 0;
    right: 0;
    left: 0;
    transform: none;
    flex-direction: row;
  }
  .nj-site .rail a {
    writing-mode: horizontal-tb;
    flex: 1;
    justify-content: center;
    text-align: center;
    border-radius: 0;
    padding: var(--nj-s4) var(--nj-s2);
  }
}
`,
  "hero.css": `/* hero — 水彩の地に、コピー + 6つの丸バブル（当院の特長） */
.nj-site .hero {
  position: relative;
  padding-block: var(--nj-s8) var(--nj-s9);
  background: var(--nj-paper);
  overflow: clip;
}
.nj-site .hero__grid {
  position: relative;
  z-index: 1;
  display: grid;
  grid-template-columns: minmax(0, 1fr) minmax(0, 0.92fr);
  gap: var(--nj-s7);
  align-items: center;
}

/* 右カラムの後ろに敷く水彩アート（差し替え可能な assets/hero-art.svg） */
.nj-site .hero__art {
  position: absolute;
  z-index: 0;
  right: -6%;
  top: 50%;
  transform: translateY(-50%);
  width: 54%;
  max-width: 540px;
  pointer-events: none;
}
.nj-site .hero__art img { display: block; width: 100%; height: auto; aspect-ratio: 600 / 620; }
.nj-site .hero__copy,
.nj-site .bubbles { position: relative; z-index: 1; }

.nj-site .hero__tagline {
  display: inline-block;
  transform: rotate(-3deg);
  font-family: var(--nj-font-head);
  font-size: 0.95rem;
  letter-spacing: 0.12em;
  color: var(--nj-primary-deep);
  background: color-mix(in srgb, var(--nj-wash-blue) 70%, #fff);
  padding: 0.35rem 1rem;
  border-radius: var(--nj-radius-pill);
  margin-bottom: var(--nj-s5);
}
.nj-site .hero__headline {
  font-size: clamp(1.9rem, 1.2rem + 3.4vw, 2.9rem);
  line-height: 1.5;
  color: var(--nj-ink);
}
.nj-site .hero__headline span { display: block; }
.nj-site .hero__headline em {
  font-style: normal;
  color: var(--nj-accent);
}
.nj-site .hero__sub {
  max-width: 30em;
  margin-top: var(--nj-s5);
  font-size: 0.96rem;
  line-height: 2;
  color: color-mix(in srgb, var(--nj-ink) 88%, #fff);
}
.nj-site .hero__cta {
  margin-top: var(--nj-s6);
  display: flex;
  gap: var(--nj-s3);
  flex-wrap: wrap;
}

/* --- バブルの塊 --- */
.nj-site .bubbles {
  position: relative;
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: var(--nj-s3);
  padding: var(--nj-s4);
}
.nj-site .bubbles li {
  aspect-ratio: 1 / 1;
  display: grid;
  place-items: center;
  text-align: center;
  padding: var(--nj-s3);
  border-radius: 50%;
  font-family: var(--nj-font-head);
  font-size: 0.8rem;
  line-height: 1.5;
  letter-spacing: 0.02em;
  color: #fff;
  background: radial-gradient(circle at 30% 28%, color-mix(in srgb, var(--nj-primary) 82%, #fff), var(--nj-primary-deep));
}
.nj-site .bubbles li:nth-child(2) { transform: translateY(-14px); }
.nj-site .bubbles li:nth-child(4) { transform: translateY(10px); }
.nj-site .bubbles li:nth-child(5) { transform: translateY(-8px); }
.nj-site .bubbles li:nth-child(3n+1) {
  background: radial-gradient(circle at 30% 28%, color-mix(in srgb, var(--nj-accent) 75%, #fff), color-mix(in srgb, var(--nj-accent) 92%, #7a5560));
}

/* --- 装飾 --- */
.nj-site .hero .wash--pink { width: 340px; height: 300px; top: -90px; left: -120px; }
.nj-site .hero .wash--blue { width: 300px; height: 280px; top: 40px; right: -110px; opacity: 0.42; }
.nj-site .hero .wash--yellow { width: 220px; height: 200px; bottom: -70px; left: 30%; opacity: 0.38; }
.nj-site .hero .wash--peach { width: 240px; height: 220px; bottom: 20px; right: 18%; opacity: 0.34; }

.nj-site .hero .botanical--tl { width: 120px; height: 150px; top: 10px; left: -6px; opacity: 0.7; }
.nj-site .hero .botanical--br { width: 150px; height: 120px; right: 0; bottom: -10px; transform: scaleX(-1); opacity: 0.6; }

@media (max-width: 860px) {
  .nj-site .hero__grid { grid-template-columns: minmax(0, 1fr); gap: var(--nj-s5); }
  .nj-site .bubbles { width: 100%; max-width: 380px; margin-inline: auto; }
  .nj-site .hero__art { display: none; }
}
@media (max-width: 460px) {
  .nj-site .bubbles { grid-template-columns: repeat(2, 1fr); }
  .nj-site .bubbles li:nth-child(2),
  .nj-site .bubbles li:nth-child(4),
  .nj-site .bubbles li:nth-child(5) { transform: none; }
}
`,
  "greeting.css": `/* greeting — 院長のことば。ポートレート（プレースホルダ）+ 署名 */
.nj-site .greeting__grid {
  display: grid;
  grid-template-columns: minmax(0, 300px) minmax(0, 1fr);
  gap: var(--nj-s7);
  align-items: center;
}
.nj-site .greeting__figure {
  position: relative;
  aspect-ratio: 4 / 5;
  border-radius: 40% 40% 46% 46% / 46% 46% 40% 40%;
  overflow: hidden;
  background: color-mix(in srgb, var(--nj-wash-peach) 60%, #fff);
}
.nj-site .greeting__figure svg,
.nj-site .greeting__figure img { width: 100%; height: 100%; object-fit: cover; }
.nj-site .greeting__body p {
  font-size: 0.97rem;
  line-height: 2.1;
}
.nj-site .greeting__body p + p { margin-top: var(--nj-s4); }
.nj-site .greeting__sign {
  margin-top: var(--nj-s6);
  font-family: var(--nj-font-head);
  color: var(--nj-ink-soft);
  font-size: 0.9rem;
}
.nj-site .greeting__sign strong {
  margin-left: var(--nj-s3);
  font-size: 1.15rem;
  font-weight: 600;
  color: var(--nj-primary-deep);
}
.nj-site .greeting .wash--mint { width: 240px; height: 220px; bottom: -80px; right: -80px; }
.nj-site .greeting .botanical--r { width: 130px; height: 170px; top: 30px; right: 8px; opacity: 0.55; }

@media (max-width: 720px) {
  .nj-site .greeting__grid { grid-template-columns: 1fr; gap: var(--nj-s6); }
  .nj-site .greeting__figure { max-width: 240px; }
}
`,
  "medical.css": `/* medical — 3〜4の診療カテゴリ + 扱う症状のことばの雲 */
.nj-site .medical__intro {
  max-width: 40em;
  margin: 0 auto var(--nj-s7);
  text-align: center;
  font-size: 0.95rem;
  line-height: 2;
  color: var(--nj-ink-soft);
}
.nj-site .medical__grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: var(--nj-s4);
}
.nj-site .medical__card {
  position: relative;
  padding: var(--nj-s5) var(--nj-s5) var(--nj-s5) var(--nj-s6);
  background: var(--nj-paper);
  border: 1px solid var(--nj-line);
  border-radius: var(--nj-radius-md);
}
.nj-site .medical__card::before {
  content: "";
  position: absolute;
  left: 0;
  top: var(--nj-s5);
  bottom: var(--nj-s5);
  width: 4px;
  border-radius: 4px;
  background: color-mix(in srgb, var(--nj-primary) 55%, var(--nj-accent));
}
.nj-site .medical__icon {
  display: grid;
  place-items: center;
  width: 46px;
  height: 46px;
  margin-bottom: var(--nj-s3);
  border-radius: 50%;
  background: color-mix(in srgb, var(--nj-wash-blue) 55%, #fff);
  color: var(--nj-primary-deep);
}
.nj-site .medical__icon svg { width: 24px; height: 24px; }

.nj-site .medical__ja {
  font-size: 1.05rem;
  color: var(--nj-ink);
}
.nj-site .medical__en {
  display: block;
  margin-top: 2px;
  font-family: var(--nj-font-head);
  font-size: 0.6rem;
  letter-spacing: 0.2em;
  text-transform: uppercase;
  color: var(--nj-primary);
}
.nj-site .medical__lead {
  margin-top: var(--nj-s3);
  font-size: 0.87rem;
  line-height: 1.95;
  color: var(--nj-ink-soft);
}

.nj-site .medical__conditions {
  margin-top: var(--nj-s7);
  text-align: center;
}
.nj-site .medical__conditions h3 {
  font-family: var(--nj-font-head);
  font-size: 0.95rem;
  color: var(--nj-primary-deep);
  margin-bottom: var(--nj-s4);
}
.nj-site .medical__tags {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  gap: var(--nj-s2);
}
.nj-site .medical__tags li {
  padding: 0.3rem 0.85rem;
  border-radius: var(--nj-radius-pill);
  background: color-mix(in srgb, var(--nj-tint) 70%, #fff);
  border: 1px solid var(--nj-line);
  font-size: 0.8rem;
  color: var(--nj-ink);
}
.nj-site .medical .wash--blue { width: 260px; height: 240px; top: -60px; right: -100px; opacity: 0.4; }
.nj-site .medical .wash--pink { width: 200px; height: 190px; bottom: 40px; left: -90px; opacity: 0.32; }

@media (max-width: 680px) {
  .nj-site .medical__grid { grid-template-columns: 1fr; }
}
`,
  "philosophy.css": `/* philosophy — 水色の帯に白文字。短い一節を中央に */
.nj-site .philosophy {
  background: linear-gradient(160deg, var(--nj-primary), var(--nj-primary-deep));
  color: #fff;
}
.nj-site .philosophy .heading .ja,
.nj-site .philosophy .heading .en { color: #fff; }
/* 見出し飾りは base.css の植物 SVG を白く反転して使う（philosophy.css は色だけ触る） */
.nj-site .philosophy__inner { text-align: center; }
.nj-site .philosophy__lead {
  font-family: var(--nj-font-head);
  font-size: clamp(1.3rem, 1rem + 1.4vw, 1.7rem);
  letter-spacing: 0.06em;
}
.nj-site .philosophy__body {
  max-width: 38em;
  margin: var(--nj-s5) auto 0;
  font-size: 0.95rem;
  line-height: 2.1;
  color: rgba(255, 255, 255, 0.92);
}
.nj-site .philosophy__body p + p { margin-top: var(--nj-s3); }
.nj-site .philosophy .botanical--c {
  width: 200px;
  height: 140px;
  left: 50%;
  bottom: 18px;
  transform: translateX(-50%);
  color: rgba(255, 255, 255, 0.5);
  opacity: 0.5;
}
`,
  "gallery.css": `/* gallery — 院内のようす。3枚の写真（差し替え用プレースホルダ）を横並び */
.nj-site .gallery__intro {
  max-width: 38em;
  margin: 0 auto var(--nj-s6);
  text-align: center;
  font-size: 0.93rem;
  line-height: 2;
  color: var(--nj-ink-soft);
}
.nj-site .gallery__grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: var(--nj-s4);
}
.nj-site .gallery__item {
  display: flex;
  flex-direction: column;
  gap: var(--nj-s3);
}
.nj-site .gallery__item img {
  width: 100%;
  aspect-ratio: 4 / 3;
  object-fit: cover;
  border-radius: var(--nj-radius-md);
  border: 1px solid var(--nj-line);
  background: color-mix(in srgb, var(--nj-tint) 55%, #fff);
}
.nj-site .gallery__cap {
  text-align: center;
  font-family: var(--nj-font-head);
  font-size: 0.82rem;
  color: var(--nj-ink-soft);
}
.nj-site .gallery .wash--peach { width: 240px; height: 220px; top: -60px; right: -90px; opacity: 0.3; }

@media (max-width: 720px) {
  .nj-site .gallery__grid { grid-template-columns: 1fr; max-width: 380px; margin-inline: auto; }
}
`,
  "schedule.css": `/* schedule — 受付時間の表。罫線は最小限、角丸で包む */
.nj-site .schedule__wrap { overflow-x: auto; }
.nj-site .schedule__table {
  width: 100%;
  min-width: 520px;
  margin-inline: auto;
  border-collapse: collapse;
  background: var(--nj-paper);
  border-radius: var(--nj-radius-md);
  overflow: hidden;
  border: 1px solid var(--nj-line);
}
.nj-site .schedule__table th,
.nj-site .schedule__table td {
  padding: var(--nj-s4) var(--nj-s3);
  text-align: center;
  font-size: 0.92rem;
  border-bottom: 1px solid var(--nj-line);
}
.nj-site .schedule__table thead th {
  font-family: var(--nj-font-head);
  color: var(--nj-primary-deep);
  background: color-mix(in srgb, var(--nj-tint) 60%, #fff);
}
.nj-site .schedule__table tbody th {
  font-weight: 400;
  color: var(--nj-ink-soft);
  white-space: nowrap;
  font-size: 0.85rem;
}
.nj-site .schedule__table tbody tr:last-child th,
.nj-site .schedule__table tbody tr:last-child td { border-bottom: 0; }
.nj-site .schedule__corner { text-align: left; color: var(--nj-ink-soft); }
.nj-site .schedule__tri { color: var(--nj-accent); font-weight: 700; }
.nj-site .schedule__notes {
  margin-top: var(--nj-s6);
  display: flex;
  flex-direction: column;
  gap: var(--nj-s2);
  text-align: center;
  font-size: 0.83rem;
  color: var(--nj-ink-soft);
}
.nj-site .schedule .wash--yellow { width: 220px; height: 200px; top: -60px; left: -80px; opacity: 0.34; }
`,
  "fees.css": `/* fees — 自費の目安。分類ごとの小さな表 */
.nj-site .fees__groups {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: var(--nj-s4);
}
.nj-site .fees__group {
  padding: var(--nj-s5);
  background: color-mix(in srgb, var(--nj-tint) 55%, #fff);
  border: 1px solid var(--nj-line);
  border-radius: var(--nj-radius-md);
}
.nj-site .fees__name {
  font-family: var(--nj-font-head);
  font-size: 0.98rem;
  color: var(--nj-primary-deep);
  padding-bottom: var(--nj-s3);
  border-bottom: 2px dotted color-mix(in srgb, var(--nj-primary) 45%, transparent);
}
.nj-site .fees__list { margin-top: var(--nj-s3); }
.nj-site .fees__row {
  display: flex;
  justify-content: space-between;
  align-items: baseline;
  gap: var(--nj-s3);
  padding: var(--nj-s3) 0;
  border-bottom: 1px solid var(--nj-line);
}
.nj-site .fees__row:last-child { border-bottom: 0; padding-bottom: 0; }
.nj-site .fees__row dt { font-size: 0.86rem; display: flex; flex-direction: column; }
.nj-site .fees__note { font-size: 0.7rem; color: var(--nj-ink-soft); }
.nj-site .fees__row dd {
  font-family: var(--nj-font-head);
  font-weight: 600;
  color: var(--nj-accent);
  white-space: nowrap;
}
.nj-site .fees__disclaimer {
  max-width: 44em;
  margin: var(--nj-s7) auto 0;
  text-align: center;
  font-size: 0.8rem;
  line-height: 1.9;
  color: var(--nj-ink-soft);
}
.nj-site .fees .wash--peach { width: 240px; height: 220px; bottom: -60px; right: -90px; opacity: 0.32; }

@media (max-width: 780px) {
  .nj-site .fees__groups { grid-template-columns: 1fr; }
}
`,
  "flow.css": `/* flow — 受診の流れ。連番の円 + 縦線 */
.nj-site .flow__list {
  display: grid;
  gap: var(--nj-s6);
  max-width: 720px;
  margin-inline: auto;
}
.nj-site .flow__step {
  position: relative;
  display: grid;
  grid-template-columns: 60px 1fr;
  gap: var(--nj-s5);
  align-items: start;
}
.nj-site .flow__step:not(:last-child)::before {
  content: "";
  position: absolute;
  left: 29px;
  top: 60px;
  bottom: calc(var(--nj-s6) * -1);
  width: 2px;
  background: color-mix(in srgb, var(--nj-primary) 30%, var(--nj-line));
}
.nj-site .flow__no {
  width: 60px;
  height: 60px;
  display: grid;
  place-items: center;
  border-radius: 50%;
  background: color-mix(in srgb, var(--nj-wash-blue) 55%, #fff);
  border: 2px solid var(--nj-primary);
  font-family: var(--nj-font-head);
  font-weight: 600;
  color: var(--nj-primary-deep);
}
.nj-site .flow__title {
  padding-top: var(--nj-s3);
  font-size: 1rem;
  color: var(--nj-ink);
  margin-bottom: var(--nj-s2);
}
.nj-site .flow__text { font-size: 0.9rem; color: var(--nj-ink-soft); }
.nj-site .flow .wash--mint { width: 220px; height: 200px; top: 40px; right: -90px; opacity: 0.34; }

@media (max-width: 520px) {
  .nj-site .flow__step { grid-template-columns: 46px 1fr; gap: var(--nj-s4); }
  .nj-site .flow__step:not(:last-child)::before { left: 22px; top: 46px; }
  .nj-site .flow__no { width: 46px; height: 46px; font-size: 0.9rem; }
}
`,
  "faq.css": `/* faq — <details> の CSS だけのアコーディオン */
.nj-site .faq__inner { max-width: 760px; margin-inline: auto; }
.nj-site .faq__list { display: grid; gap: var(--nj-s3); }
.nj-site .faq__item {
  background: var(--nj-paper);
  border: 1px solid var(--nj-line);
  border-radius: var(--nj-radius-md);
  overflow: hidden;
}
.nj-site .faq__q {
  display: flex;
  align-items: center;
  gap: var(--nj-s3);
  padding: var(--nj-s4) var(--nj-s5);
  cursor: pointer;
  list-style: none;
  font-family: var(--nj-font-head);
  font-size: 0.94rem;
  color: var(--nj-ink);
}
.nj-site .faq__q::-webkit-details-marker { display: none; }
.nj-site .faq__mark {
  flex-shrink: 0;
  width: 1.6rem;
  height: 1.6rem;
  display: grid;
  place-items: center;
  border-radius: 50%;
  font-family: var(--nj-font-head);
  font-weight: 700;
  font-size: 0.78rem;
}
.nj-site .faq__mark--q { background: var(--nj-primary); color: #fff; }
.nj-site .faq__mark--a { background: color-mix(in srgb, var(--nj-accent) 22%, #fff); color: var(--nj-accent); }
.nj-site .faq__qtext { flex: 1; }
.nj-site .faq__chev {
  flex-shrink: 0;
  width: 9px;
  height: 9px;
  border-right: 2px solid var(--nj-primary);
  border-bottom: 2px solid var(--nj-primary);
  transform: rotate(45deg);
  transition: transform 0.25s ease;
}
.nj-site .faq__item[open] .faq__chev { transform: rotate(225deg); }
.nj-site .faq__a {
  display: flex;
  gap: var(--nj-s3);
  padding: 0 var(--nj-s5) var(--nj-s5);
  font-size: 0.88rem;
  line-height: 1.95;
  color: var(--nj-ink-soft);
}
.nj-site .faq .wash--pink { width: 220px; height: 200px; bottom: -60px; left: -80px; opacity: 0.3; }
`,
  "news.css": `/* news — 日付 + 見出しの素朴な一覧 */
.nj-site .news__list {
  max-width: 720px;
  margin-inline: auto;
  border-top: 1px solid var(--nj-line);
}
.nj-site .news__list li {
  display: flex;
  gap: var(--nj-s5);
  align-items: baseline;
  padding: var(--nj-s4) 0;
  border-bottom: 1px solid var(--nj-line);
}
.nj-site .news__date {
  flex-shrink: 0;
  width: 6rem;
  font-family: var(--nj-font-head);
  font-size: 0.85rem;
  color: var(--nj-primary-deep);
}
.nj-site .news__title { font-size: 0.92rem; }
.nj-site .news .botanical--l { width: 120px; height: 150px; top: 30px; left: -4px; opacity: 0.5; }

@media (max-width: 520px) {
  .nj-site .news__list li { flex-direction: column; gap: 2px; }
}
`,
  "access.css": `/* access — 左に案内、右に地図（プレースホルダ） */
.nj-site .access__grid {
  display: grid;
  grid-template-columns: minmax(0, 1fr) minmax(0, 1fr);
  gap: var(--nj-s7);
  align-items: start;
}
.nj-site .access__address {
  font-family: var(--nj-font-head);
  font-size: 1.02rem;
  color: var(--nj-primary-deep);
}
.nj-site .access__points {
  margin-top: var(--nj-s4);
  display: flex;
  flex-direction: column;
  gap: var(--nj-s2);
  font-size: 0.88rem;
}
.nj-site .access__points li::before { content: "・"; color: var(--nj-accent); }
.nj-site .access__info {
  margin-top: var(--nj-s6);
  padding-top: var(--nj-s5);
  border-top: 1px solid var(--nj-line);
  font-size: 0.88rem;
}
.nj-site .access__info-row + .access__info-row { margin-top: var(--nj-s3); }
.nj-site .access__info dt {
  font-family: var(--nj-font-head);
  color: var(--nj-ink-soft);
}
.nj-site .access__tel {
  display: inline-block;
  margin-top: var(--nj-s6);
  font-family: var(--nj-font-head);
  font-size: 1.4rem;
  font-weight: 600;
  color: var(--nj-primary-deep);
}
.nj-site .access__map {
  aspect-ratio: 4 / 3;
  border-radius: var(--nj-radius-md);
  overflow: hidden;
  border: 1px solid var(--nj-line);
}
.nj-site .access__map svg,
.nj-site .access__map img { width: 100%; height: 100%; object-fit: cover; }

@media (max-width: 760px) {
  .nj-site .access__grid { grid-template-columns: 1fr; gap: var(--nj-s6); }
}
`,
  "contact.css": `/* contact — 淡色の地に、水彩がかった白カード。予約と電話を並べる */
.nj-site .contact__card {
  position: relative;
  overflow: hidden;
  max-width: 780px;
  margin-inline: auto;
  padding: clamp(2rem, 1rem + 4vw, 3.25rem);
  border-radius: var(--nj-radius-lg);
  background: #fff;
  border: 1px solid var(--nj-line);
  text-align: center;
}
.nj-site .contact__card .wash--pink { width: 200px; height: 180px; top: -60px; left: -60px; opacity: 0.4; }
.nj-site .contact__card .wash--blue { width: 200px; height: 180px; bottom: -60px; right: -60px; opacity: 0.4; }
.nj-site .contact__en {
  font-family: var(--nj-font-head);
  font-size: 0.78rem;
  letter-spacing: 0.26em;
  text-transform: uppercase;
  color: var(--nj-primary);
}
.nj-site .contact__ja {
  margin-top: var(--nj-s2);
  font-size: clamp(1.35rem, 1.05rem + 1.3vw, 1.7rem);
}
.nj-site .contact__lead {
  max-width: 36em;
  margin: var(--nj-s4) auto 0;
  font-size: 0.9rem;
  line-height: 2;
  color: var(--nj-ink-soft);
}
.nj-site .contact__actions {
  position: relative;
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  gap: var(--nj-s3);
  margin-top: var(--nj-s6);
}
.nj-site .contact__tel {
  display: inline-flex;
  flex-direction: column;
  align-items: center;
  gap: 2px;
  padding: 0.7rem 1.8rem;
  border-radius: var(--nj-radius-pill);
  border: 1.5px solid color-mix(in srgb, var(--nj-primary) 45%, transparent);
  color: var(--nj-primary-deep);
  font-family: var(--nj-font-head);
}
.nj-site .contact__tel small {
  font-size: 0.66rem;
  font-weight: 400;
  letter-spacing: 0.12em;
  color: var(--nj-ink-soft);
}
.nj-site .contact__tel b { font-size: 1.1rem; font-weight: 600; }
.nj-site .contact__note {
  position: relative;
  margin-top: var(--nj-s5);
  font-size: 0.76rem;
  color: var(--nj-ink-soft);
}

@media (max-width: 460px) {
  .nj-site .contact__actions .btn,
  .nj-site .contact__tel { width: 100%; }
}
`,
  "footer.css": `/* footer — 濃い水色の帯 */
.nj-site .site-footer {
  background: var(--nj-primary-deep);
  color: rgba(255, 255, 255, 0.9);
  padding-top: var(--nj-section-pad);
}
.nj-site .site-footer__grid {
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
  gap: var(--nj-s7);
}
.nj-site .site-footer__name {
  font-family: var(--nj-font-head);
  font-size: 1.15rem;
  font-weight: 600;
  color: #fff;
}
.nj-site .site-footer__en {
  font-size: 0.6rem;
  letter-spacing: 0.24em;
  text-transform: uppercase;
  color: rgba(255, 255, 255, 0.6);
}
.nj-site .site-footer__addr {
  margin-top: var(--nj-s4);
  font-size: 0.83rem;
  line-height: 1.95;
}
.nj-site .site-footer__tel {
  display: inline-block;
  margin-top: var(--nj-s3);
  font-family: var(--nj-font-head);
  font-size: 1.2rem;
  font-weight: 600;
  color: #fff;
}
.nj-site .site-footer__nav {
  display: grid;
  gap: var(--nj-s2);
  align-content: start;
}
.nj-site .site-footer__nav a { font-size: 0.83rem; color: rgba(255, 255, 255, 0.8); }
.nj-site .site-footer__nav a:hover { color: #fff; }
.nj-site .site-footer__copy {
  margin-top: var(--nj-s7);
  padding: var(--nj-s4);
  text-align: center;
  font-size: 0.72rem;
  color: rgba(255, 255, 255, 0.55);
  border-top: 1px solid rgba(255, 255, 255, 0.12);
}
`,
};

/** Order the <link> tags are emitted in (source order = cascade order). */
export const CSS_ORDER = ["base.css","header.css","hero.css","greeting.css","medical.css","philosophy.css","gallery.css","schedule.css","fees.css","flow.css","faq.css","news.css","access.css","contact.css","footer.css"];

export const SITE_JS = `/*
 * nj-motion.js — /preview/<slug> 用の控えめな進歩的拡張。依存なし・1ファイル。
 *
 * これが読み込まれなくても表示は完全に成立する(下の機能はすべて「無くても困らない」もの):
 *   1. スクロールで要素をふわっと出す (.nj-reveal / [data-nj-anim] に .is-visible)
 *   2. [data-nj-count] の数字を 0 から数え上げ
 *   3. ヘッダーにスクロール時の影 / 上部のスクロール進捗バー / Hero 背景の視差
 *   4. ページ内アンカーのスクロール。sticky ヘッダーの高さ分を差し引いて止める
 *      (ホーム = #top はページ最上部へ)。あわせてモバイルメニューを閉じる
 *
 * prefers-reduced-motion では動きを止め、要素は最初から見えるようにする。
 */
(function () {
  "use strict";

  var root = document.querySelector(".nj-site");
  if (!root) return;

  var reduce =
    window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  var hasIO = "IntersectionObserver" in window;

  // JS が動いていることを CSS に伝える。これで初期状態(opacity:0)が有効になる。
  root.classList.add("nj-js");

  // --- 1 & 2. reveal + count-up -----------------------------------------------
  var revealSel = ".nj-reveal, [data-nj-anim]";
  var items = [].slice.call(root.querySelectorAll(revealSel));

  // 同じ親の中で data-nj-anim を持つ要素だけを数える(カード列などの段差用)。
  // トップレベルの .nj-reveal セクション同士では段差を付けない。
  function staggerIndex(el) {
    var p = el.parentNode;
    if (!p) return 0;
    var sibs = [].slice.call(p.children).filter(function (c) {
      return c.nodeType === 1 && c.hasAttribute && c.hasAttribute("data-nj-anim");
    });
    var i = sibs.indexOf(el);
    return i < 0 ? 0 : Math.min(i, 6);
  }

  function pad(v, n) {
    var s = String(v);
    while (n && s.length < n) s = "0" + s;
    return s;
  }

  function countUp(scope) {
    var nodes = scope.hasAttribute && scope.hasAttribute("data-nj-count")
      ? [scope]
      : [].slice.call(scope.querySelectorAll("[data-nj-count]"));
    nodes.forEach(function (n) {
      if (n.__njCounted) return;
      n.__njCounted = true;
      var target = parseFloat(n.getAttribute("data-nj-count"));
      var p = n.getAttribute("data-nj-pad");
      var suffix = n.getAttribute("data-nj-suffix") || "";
      if (reduce || isNaN(target) || !window.requestAnimationFrame) {
        n.textContent = pad(isNaN(target) ? n.textContent : target, p) + suffix;
        return;
      }
      var dur = 900;
      var t0 = performance.now();
      (function tick(now) {
        var k = Math.min(1, (now - t0) / dur);
        var e = 1 - Math.pow(1 - k, 3);
        n.textContent = pad(Math.round(target * e), p) + suffix;
        if (k < 1) requestAnimationFrame(tick);
      })(t0);
    });
  }

  function show(el) {
    if (el.hasAttribute("data-nj-anim")) {
      var i = staggerIndex(el);
      if (i > 0) el.style.setProperty("--nj-anim-delay", (i * 0.08).toFixed(2) + "s");
    }
    el.classList.add("is-visible");
    countUp(el);
  }

  if (reduce || !hasIO) {
    items.forEach(function (el) {
      el.classList.add("is-visible");
      countUp(el);
    });
  } else {
    var io = new IntersectionObserver(
      function (entries) {
        entries.forEach(function (en) {
          if (!en.isIntersecting) return;
          show(en.target);
          io.unobserve(en.target);
        });
      },
      { rootMargin: "0px 0px -12% 0px", threshold: 0.12 }
    );
    items.forEach(function (el) {
      io.observe(el);
    });
  }

  // --- 3. header shadow / progress bar / hero parallax -----------------------
  var header = root.querySelector("header");
  var progress = root.querySelector(".nj-progress");
  var parallax = root.querySelector("[data-nj-parallax]");
  var ticking = false;

  // sticky ヘッダーの実測高さを CSS 変数に入れておく(scroll-margin-top の素の挙動用)。
  function headerHeight() {
    return header ? Math.round(header.getBoundingClientRect().height) : 0;
  }
  function measureHeader() {
    root.style.setProperty("--nj-header-h", headerHeight() + "px");
  }
  measureHeader();
  window.addEventListener("resize", measureHeader, { passive: true });

  function onScroll() {
    if (ticking) return;
    ticking = true;
    (window.requestAnimationFrame || function (f) { f(); })(function () {
      var y = window.pageYOffset || document.documentElement.scrollTop || 0;

      if (header) {
        if (y > 8) header.setAttribute("data-nj-scrolled", "");
        else header.removeAttribute("data-nj-scrolled");
      }

      if (progress) {
        var h =
          (document.documentElement.scrollHeight || 0) - window.innerHeight;
        progress.style.width = (h > 0 ? Math.min(100, (y / h) * 100) : 0) + "%";
      }

      if (parallax && !reduce && y < 1000) {
        parallax.style.transform =
          "translate3d(0," + (y * 0.12).toFixed(1) + "px,0) scale(1.12)";
      }

      ticking = false;
    });
  }

  window.addEventListener("scroll", onScroll, { passive: true });
  window.addEventListener("resize", onScroll, { passive: true });
  onScroll();

  // --- 4. anchor scroll (ヘッダー高さ分を差し引く) + close mobile menu -------
  document.addEventListener("click", function (e) {
    var a = e.target && e.target.closest && e.target.closest('a[href^="#"]');
    if (!a) return;
    var id = a.getAttribute("href").slice(1);
    if (!id) return;
    var el = document.getElementById(id);
    if (!el) return;
    e.preventDefault();

    var toggle = document.getElementById("nj-nav");
    if (toggle) toggle.checked = false; // 先に閉じてからヘッダー高さを測る

    var y = 0;
    if (id !== "top") {
      var top = el.getBoundingClientRect().top + (window.pageYOffset || 0);
      y = Math.max(0, Math.round(top - headerHeight() - 8));
    }
    var smooth = !reduce && "scrollBehavior" in document.documentElement.style;
    if (smooth) window.scrollTo({ top: y, behavior: "smooth" });
    else window.scrollTo(0, y);

    if (window.history && history.replaceState) {
      history.replaceState(null, "", "#" + id);
    }
  });
})();
`;

/** Botanical line-art <symbol> defs; referenced via <use href="#bot-*"/>. */
export const BOTANICAL_DEFS = `<svg width="0" height="0" style="position:absolute" aria-hidden="true">
    <symbol id="bot-sprig" viewBox="0 0 60 90">
      <g fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round">
        <path d="M30 88 C31 62 24 44 30 10"/>
        <path d="M29 70 C20 66 15 58 14 48 C24 50 30 58 29 70Z"/>
        <path d="M30 56 C39 52 44 44 45 34 C35 36 29 44 30 56Z"/>
        <path d="M29 40 C21 37 17 30 16 22 C25 24 30 31 29 40Z"/>
        <circle cx="30" cy="12" r="2.4"/>
      </g>
    </symbol>
    <symbol id="bot-flower" viewBox="0 0 70 62">
      <g fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round">
        <path d="M35 32 C27 22 28 12 34 10 C40 8 44 16 40 24 C48 16 58 20 54 30 C62 32 62 44 52 44 C54 54 42 58 38 48 C34 58 22 54 24 44 C14 44 14 32 22 30 C16 20 26 14 34 22"/>
        <circle cx="37" cy="32" r="4"/>
        <path d="M37 36 C41 48 47 54 66 58"/>
      </g>
    </symbol>
  </svg>
`;

/** Decorative + fallback-photo SVGs written verbatim into every bundle's assets/ dir.
 *  hero-art is behind the hero copy at low opacity; the *doctor* / *room-* / *map* files are
 *  placeholders shown only when no real or OpenAI-generated image is available for that slot. */
export const ASSET_SVGS: Record<string, string> = {
  "hero-art.svg": `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="620" viewBox="0 0 600 620" role="img" aria-label="やわらかな水彩と植物のイラスト">
  <defs>
    <radialGradient id="w1" cx="35%" cy="30%" r="70%">
      <stop offset="0" stop-color="#f2cdd6" stop-opacity="0.9"/>
      <stop offset="1" stop-color="#f2cdd6" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="w2" cx="65%" cy="45%" r="70%">
      <stop offset="0" stop-color="#c9dcee" stop-opacity="0.9"/>
      <stop offset="1" stop-color="#c9dcee" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="w3" cx="45%" cy="72%" r="60%">
      <stop offset="0" stop-color="#f3e7b6" stop-opacity="0.85"/>
      <stop offset="1" stop-color="#f3e7b6" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="w4" cx="70%" cy="70%" r="55%">
      <stop offset="0" stop-color="#f4d6c0" stop-opacity="0.8"/>
      <stop offset="1" stop-color="#f4d6c0" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <rect width="600" height="620" fill="#fffdf8"/>
  <circle cx="215" cy="200" r="220" fill="url(#w1)"/>
  <circle cx="400" cy="290" r="230" fill="url(#w2)"/>
  <circle cx="270" cy="450" r="190" fill="url(#w3)"/>
  <circle cx="430" cy="440" r="170" fill="url(#w4)"/>
  <g fill="none" stroke="#c9bda4" stroke-width="2" stroke-linecap="round">
    <path d="M120 560 C124 470 96 400 122 300"/>
    <path d="M116 500 C86 492 70 468 66 436 C102 442 122 468 116 500Z"/>
    <path d="M122 440 C154 428 172 400 176 366 C138 372 118 402 122 440Z"/>
    <path d="M116 372 C88 360 74 338 70 306 C104 314 120 340 116 372Z"/>
    <circle cx="122" cy="300" r="4"/>
  </g>
  <g fill="none" stroke="#c9bda4" stroke-width="2" stroke-linecap="round">
    <path d="M470 90 C470 90 442 60 460 40 C476 22 500 44 486 66 C512 46 540 62 522 88 C548 96 548 130 514 130 C520 156 480 168 466 138 C452 168 414 154 420 128 C392 128 392 96 418 90 C400 66 428 48 450 70"/>
    <circle cx="466" cy="90" r="8"/>
    <path d="M466 100 C476 138 494 156 540 168"/>
  </g>
</svg>
`,
  "doctor.svg": `<svg xmlns="http://www.w3.org/2000/svg" width="400" height="500" viewBox="0 0 400 500" role="img" aria-label="院長の写真（プレースホルダ）">
  <rect width="400" height="500" fill="#f6e7db"/>
  <circle cx="200" cy="150" r="180" fill="#f2ddcd"/>
  <g fill="none" stroke="#c9bda4" stroke-width="2.4" stroke-linecap="round">
    <path d="M40 470 C40 380 110 320 200 320 C290 320 360 380 360 470"/>
    <circle cx="200" cy="196" r="78"/>
    <path d="M150 250 C150 300 120 330 120 360 M250 250 C250 300 280 330 280 360"/>
    <path d="M168 470 C168 400 176 372 176 372 M232 470 C232 400 224 372 224 372"/>
  </g>
  <path d="M150 250 C170 274 230 274 250 250" fill="none" stroke="#c9bda4" stroke-width="2.4" stroke-linecap="round"/>
  <text x="200" y="452" text-anchor="middle" font-family="'Klee One', serif" font-size="15" fill="#a99a80" letter-spacing="2">Photo</text>
</svg>
`,
  "room-1.svg": `<svg xmlns="http://www.w3.org/2000/svg" width="640" height="480" viewBox="0 0 640 480" role="img" aria-label="待合スペースの写真（プレースホルダ）">
  <rect width="640" height="480" fill="#fbf5ea"/>
  <circle cx="150" cy="140" r="150" fill="#f2cdd6" opacity="0.35"/>
  <circle cx="500" cy="200" r="170" fill="#c9dcee" opacity="0.35"/>
  <g fill="none" stroke="#b8ab97" stroke-width="3" stroke-linecap="round" stroke-linejoin="round">
    <rect x="70" y="70" width="180" height="150" rx="6"/>
    <path d="M70 145 H250 M160 70 V220"/>
    <path d="M120 300 h300 a24 24 0 0 1 24 24 v70 h-348 v-70 a24 24 0 0 1 24 -24Z"/>
    <path d="M120 324 h300 M180 300 v-16 a12 12 0 0 1 24 0 v16 M330 300 v-16 a12 12 0 0 1 24 0 v16"/>
    <path d="M96 394 v46 M444 394 v46"/>
    <path d="M520 300 c-30 0 -46 30 -40 70 c4 30 8 70 40 70 s36 -40 40 -70 c6 -40 -10 -70 -40 -70Z"/>
    <path d="M520 300 v-40 M520 276 c-14 -10 -28 -6 -30 8 c14 4 26 0 30 -8Z M520 286 c14 -12 30 -8 32 6 c-14 6 -28 2 -32 -6Z"/>
  </g>
  <text x="320" y="452" text-anchor="middle" font-family="'Klee One', serif" font-size="16" fill="#a99a80" letter-spacing="2">待合スペース</text>
</svg>
`,
  "room-2.svg": `<svg xmlns="http://www.w3.org/2000/svg" width="640" height="480" viewBox="0 0 640 480" role="img" aria-label="受付の写真（プレースホルダ）">
  <rect width="640" height="480" fill="#fbf5ea"/>
  <circle cx="480" cy="130" r="150" fill="#f3e7b6" opacity="0.4"/>
  <circle cx="130" cy="230" r="160" fill="#f4d6c0" opacity="0.35"/>
  <g fill="none" stroke="#b8ab97" stroke-width="3" stroke-linecap="round" stroke-linejoin="round">
    <path d="M110 250 h420 v150 h-420Z"/>
    <path d="M110 250 l40 -34 h340 l40 34 M150 216 v-40 h340 v40"/>
    <path d="M180 400 v-110 M320 400 v-110 M460 400 v-110 M110 340 h420"/>
    <rect x="196" y="120" width="90" height="66" rx="4"/>
    <rect x="300" y="120" width="90" height="66" rx="4"/>
    <path d="M196 153 h90 M300 153 h90 M241 120 v66 M345 120 v66"/>
    <circle cx="560" cy="300" r="26"/>
    <path d="M560 326 v70 M540 350 h40"/>
  </g>
  <text x="320" y="452" text-anchor="middle" font-family="'Klee One', serif" font-size="16" fill="#a99a80" letter-spacing="2">受付</text>
</svg>
`,
  "room-3.svg": `<svg xmlns="http://www.w3.org/2000/svg" width="640" height="480" viewBox="0 0 640 480" role="img" aria-label="診察室の写真（プレースホルダ）">
  <rect width="640" height="480" fill="#fbf5ea"/>
  <circle cx="500" cy="150" r="160" fill="#c9dcee" opacity="0.4"/>
  <circle cx="150" cy="300" r="150" fill="#d0e4d8" opacity="0.45"/>
  <g fill="none" stroke="#b8ab97" stroke-width="3" stroke-linecap="round" stroke-linejoin="round">
    <path d="M120 380 h180 a20 20 0 0 1 20 20 v20 h-240 v-40 a20 20 0 0 1 20 -20Z" transform="translate(60 -30)"/>
    <path d="M180 350 v-70 a26 26 0 0 1 52 0 v70 M232 300 h90 a14 14 0 0 1 0 28 h-90"/>
    <path d="M430 110 v120 M410 110 h40 M430 230 a30 30 0 0 0 -30 30 M430 260 h2"/>
    <path d="M470 300 h120 v150 h-120Z M470 350 h120 M530 300 v150"/>
    <path d="M300 150 c8 -14 26 -14 34 0 c6 12 6 24 -2 36 c-6 8 -15 14 -15 14 s-9 -6 -15 -14 c-8 -12 -8 -24 -2 -36Z"/>
  </g>
  <text x="320" y="452" text-anchor="middle" font-family="'Klee One', serif" font-size="16" fill="#a99a80" letter-spacing="2">診察室</text>
</svg>
`,
  "map.svg": `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="460" viewBox="0 0 600 460" role="img" aria-label="周辺地図（プレースホルダ）">
  <rect width="600" height="460" fill="#eef2ea"/>
  <g stroke="#dbe3d4" stroke-width="10" fill="none">
    <path d="M0 300 H600 M0 150 H600 M230 0 V460 M420 0 V460"/>
  </g>
  <path d="M0 300 L600 150" stroke="#e7d8c6" stroke-width="14"/>
  <rect x="60" y="60" width="120" height="60" rx="6" fill="#dfe8f0"/>
  <text x="120" y="96" text-anchor="middle" font-family="'Klee One', serif" font-size="15" fill="#7f97ab">○○駅</text>
  <rect x="460" y="330" width="90" height="70" rx="8" fill="#d7e6da"/>
  <text x="505" y="372" text-anchor="middle" font-family="'Klee One', serif" font-size="13" fill="#7a9a7f">公園</text>
  <g transform="translate(300 210)">
    <circle r="17" fill="#7aa9d8"/>
    <path d="M0 15 C-14 37 -30 41 -30 59 A30 30 0 0 0 30 59 C30 41 14 37 0 15Z" fill="#7aa9d8"/>
    <circle cy="2" r="7" fill="#fffdf8"/>
  </g>
  <text x="300" y="300" text-anchor="middle" font-family="'Klee One', serif" font-size="15" fill="#8b8579">ひだまり皮ふ科クリニック</text>
</svg>
`,
};
